#!/usr/bin/env python3
"""Strategy Information & Metadata Table Generator.

Inserts a comprehensive 'info' table into a target DuckDB database documenting
all strategy columns with the schema:
    (clmn_name VARCHAR PRIMARY KEY, brif VARCHAR, calcuation VARCHAR, remars VARCHAR)

Usage:
    uv run python Utils/strategy_info.py --target Shared/Data/classic_floor_mod-v5-1.duckdb
    uv run python classic_floor_mod_v6-info.py --target Shared/Data/classic_floor_mod-v5-1.duckdb
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Any

import duckdb
import pandas as pd
from rich.console import Console
from rich.table import Table

console = Console()

# Comprehensive Master Data Dictionary of Strategy Columns
COLUMN_DICTIONARY: dict[str, dict[str, str]] = {
    # 1. Trade Identification & Metadata
    "uid": {
        "clmn_name": "uid",
        "brif": "Unique integer primary key assigned sequentially across trades",
        "calcuation": "ROW_NUMBER() OVER (ORDER BY entry_time ASC) (integers 1..N)",
        "remars": "Primary key used to join with auxiliary tables and excursion views",
    },
    "trade_id": {
        "clmn_name": "trade_id",
        "brif": "Chronological sequential trade identifier assigned per executed trade",
        "calcuation": "Incremental integer counter assigned per executed position (1, 2, 3...)",
        "remars": "Preserves sequential execution order; unique per trade branch",
    },
    "vbt_trade_id": {
        "clmn_name": "vbt_trade_id",
        "brif": "VectorBT simulation engine trade index",
        "calcuation": "Native trade record identifier generated by VectorBT portfolio simulation",
        "remars": "Maps VectorBT Portfolio.trades records to DuckDB rows",
    },
    "fingerprint": {
        "clmn_name": "fingerprint",
        "brif": "SHA-256 hash uniquely fingerprinting strategy configuration and parameters",
        "calcuation": "SHA256(strategy_name + symbol + timeframe + params_json)",
        "remars": "Ensures audit reproducibility and prevents parameter collision across runs",
    },
    "strategy_name": {
        "clmn_name": "strategy_name",
        "brif": "Registered strategy identifier string",
        "calcuation": "Static strategy name string (e.g. 'classic_floor_mod_v6')",
        "remars": "Used for multi-strategy partitioning and registry lookups",
    },
    "symbol": {
        "clmn_name": "symbol",
        "brif": "Market currency pair or ticker symbol",
        "calcuation": "Asset identifier string (e.g. 'EURUSD')",
        "remars": "Forex / crypto market instrument identifier",
    },
    "timeframe": {
        "clmn_name": "timeframe",
        "brif": "Candlestick aggregation timeframe",
        "calcuation": "Bar aggregation period string (e.g. '5m', '1m', '1h')",
        "remars": "Base candle resolution used for indicator calculation and simulation",
    },
    "window_start": {
        "clmn_name": "window_start",
        "brif": "Start timestamp of the backtest simulation window",
        "calcuation": "Timestamp of the first candle evaluated in the backtest chunk",
        "remars": "Used in monthly/windowed chunk simulations",
    },
    "window_end": {
        "clmn_name": "window_end",
        "brif": "End timestamp of the backtest simulation window",
        "calcuation": "Timestamp of the final candle evaluated in the backtest chunk",
        "remars": "Used in monthly/windowed chunk simulations",
    },
    "direction": {
        "clmn_name": "direction",
        "brif": "Trade execution direction side ('LONG' | 'SHORT')",
        "calcuation": "Position side string: 'LONG' or 'SHORT'",
        "remars": "Currently 'LONG' for floor trader support bounce setups",
    },
    "status": {
        "clmn_name": "status",
        "brif": "Trade lifecycle state ('CLOSED' | 'OPEN')",
        "calcuation": "'CLOSED' for finalized positions, 'OPEN' for active positions",
        "remars": "Finalized trades in storage tables are marked 'CLOSED'",
    },
    "session": {
        "clmn_name": "session",
        "brif": "Forex market trading session active at entry timestamp",
        "calcuation": "Asian (21:00-07:00 UTC), London (07:00-12:00 UTC), London/NY Overlap (12:00-16:00 UTC), New York (16:00-21:00 UTC)",
        "remars": "Categorical session tag for session-based loss profile breakdowns",
    },

    # 2. 4-Phase Lifecycle Timestamps
    "signal_time": {
        "clmn_name": "signal_time",
        "brif": "Timestamp of initial setup trigger bar where bounce condition was detected (Bar 0)",
        "calcuation": "Timestamp of candle satisfying Close <= lower_pivot",
        "remars": "Phase 1 of 4-phase lifecycle; anchors pivot, upper_pivot, and primary_sl",
    },
    "confirmation_time": {
        "clmn_name": "confirmation_time",
        "brif": "Timestamp of setup confirmation candle (Bar +3 Open)",
        "calcuation": "Timestamp of the 4th candle from signal bar (signal_bar + 3)",
        "remars": "Phase 2 of 4-phase lifecycle; signals when entry order is confirmed",
    },
    "entry_time": {
        "clmn_name": "entry_time",
        "brif": "Exact timestamp when broker order fill occurs",
        "calcuation": "Timestamp of execution fill (equals confirmation_time for market orders)",
        "remars": "Phase 3 of 4-phase lifecycle; decoupled from confirmation to support pending/limit orders",
    },
    "exit_time": {
        "clmn_name": "exit_time",
        "brif": "Exact timestamp when position is closed",
        "calcuation": "Timestamp of candle where TP, SL, or session cutoff triggered",
        "remars": "Phase 4 of 4-phase lifecycle; marks trade termination",
    },

    # 3. Execution & Order Levels
    "entry_price": {
        "clmn_name": "entry_price",
        "brif": "Execution fill price of the trade",
        "calcuation": "Open price of the confirmation candle (Bar +3 Open)",
        "remars": "Benchmark price for all risk, return, MFE, and MAE calculations",
    },
    "exit_price": {
        "clmn_name": "exit_price",
        "brif": "Fill price at trade termination",
        "calcuation": "tp_price on TP hit, safe_sl on SL hit, or candle close on session cutoff",
        "remars": "Realized fill price used to calculate net PnL and point gain",
    },
    "tp_price": {
        "clmn_name": "tp_price",
        "brif": "Take Profit target price level",
        "calcuation": "Frozen upper_pivot (R1) captured from signal bar (Bar 0)",
        "remars": "Fixed profit target level; triggers trade exit when High >= tp_price",
    },
    "swing_low": {
        "clmn_name": "swing_low",
        "brif": "Lowest candle body low across setup window",
        "calcuation": "min(min(Open, Close)) across Bars 0 to 3 (signal through confirmation)",
        "remars": "Used as the structural floor anchor for computing safe_sl",
    },

    # 4. Pivot & Channel Geometry
    "pivot": {
        "clmn_name": "pivot",
        "brif": "20-period rolling Floor Trader Pivot level shifted by 1 bar",
        "calcuation": "(rolling_high_20 + rolling_low_20 + close[-1]) / 3",
        "remars": "Central equilibrium axis of the floor trader system",
    },
    "lower_pivot": {
        "clmn_name": "lower_pivot",
        "brif": "Generalized lower channel support boundary (Floor S1)",
        "calcuation": "(2 * pivot) - rolling_high_20",
        "remars": "Canonical replacement for s1; serves as primary setup bounce trigger (Close <= lower_pivot)",
    },
    "upper_pivot": {
        "clmn_name": "upper_pivot",
        "brif": "Generalized upper channel resistance boundary (Floor R1)",
        "calcuation": "(2 * pivot) - rolling_low_20",
        "remars": "Canonical replacement for r1; serves as fixed Take Profit target (tp_price)",
    },
    "s1": {
        "clmn_name": "s1",
        "brif": "Floor Support 1 line (legacy duplicate of lower_pivot)",
        "calcuation": "(2 * pivot) - rolling_high_20",
        "remars": "Purged in v6; retained in v5 for backwards compatibility",
    },
    "r1": {
        "clmn_name": "r1",
        "brif": "Floor Resistance 1 line (legacy duplicate of upper_pivot)",
        "calcuation": "(2 * pivot) - rolling_low_20",
        "remars": "Purged in v6; retained in v5 for backwards compatibility",
    },

    # 5. Multi-Tier Stop Loss Hierarchy
    "primary_sl": {
        "clmn_name": "primary_sl",
        "brif": "Aggressive Stop Loss price level anchored directly to setup candle Close",
        "calcuation": "Close price of setup signal candle (Bar 0 Close)",
        "remars": "Aggressive tight stop model for tight-risk benchmarking",
    },
    "pivot_sl": {
        "clmn_name": "pivot_sl",
        "brif": "Structural Stop Loss price level anchored directly to lower pivot",
        "calcuation": "lower_pivot (S1) support level captured from signal candle",
        "remars": "Structural floor support stop model",
    },
    "safe_sl": {
        "clmn_name": "safe_sl",
        "brif": "Conservative dynamic Stop Loss incorporating swing low and channel buffer",
        "calcuation": "swing_low - 0.5 * (upper_pivot - lower_pivot)",
        "remars": "Active protective stop loss; incorporates swing body low buffer to avoid market noise",
    },
    "sl_price": {
        "clmn_name": "sl_price",
        "brif": "Dynamic Stop Loss price level (legacy duplicate of safe_sl)",
        "calcuation": "swing_low - 0.5 * (upper_pivot - lower_pivot)",
        "remars": "Purged in v6; retained in v5 for backwards compatibility",
    },

    # 6. Multi-Tier In-Trade SL Breaches
    "primary_sl_hit": {
        "clmn_name": "primary_sl_hit",
        "brif": "Telemetry flag indicating whether price touched primary_sl while in trade",
        "calcuation": "True if min(Low[entry..exit]) <= primary_sl else False",
        "remars": "Diagnostic breach flag; when True on winning trades, reveals premature stop-out risk",
    },
    "pivot_sl_hit": {
        "clmn_name": "pivot_sl_hit",
        "brif": "Telemetry flag indicating whether price touched pivot_sl while in trade",
        "calcuation": "True if min(Low[entry..exit]) <= pivot_sl else False",
        "remars": "Diagnostic breach flag for structural support breaches during trade lifecycle",
    },
    "safe_sl_hit": {
        "clmn_name": "safe_sl_hit",
        "brif": "Telemetry flag indicating whether price touched safe_sl while in trade",
        "calcuation": "True if min(Low[entry..exit]) <= safe_sl else False",
        "remars": "Directly coincides with SL exit trigger on losing trades",
    },

    # 7. Risk Distances, Sizing & Fees
    "risk_primary": {
        "clmn_name": "risk_primary",
        "brif": "Absolute price risk distance from entry to primary_sl",
        "calcuation": "max(entry_price - primary_sl, 1e-6)",
        "remars": "Measure of price points risked under aggressive primary SL model",
    },
    "risk_pivot": {
        "clmn_name": "risk_pivot",
        "brif": "Absolute price risk distance from entry to pivot_sl",
        "calcuation": "max(entry_price - pivot_sl, 1e-6)",
        "remars": "Measure of price points risked under structural lower_pivot SL model",
    },
    "risk_safe": {
        "clmn_name": "risk_safe",
        "brif": "Absolute price risk distance from entry to conservative safe_sl",
        "calcuation": "max(entry_price - safe_sl, 1e-6)",
        "remars": "Primary risk distance metric used for position sizing and capital allocation",
    },
    "size": {
        "clmn_name": "size",
        "brif": "Dynamic position volume in units / contracts",
        "calcuation": "risk_per_trade / risk_safe",
        "remars": "Volatility-adjusted unit sizing ensuring fixed monetary risk per trade",
    },
    "lot_size": {
        "clmn_name": "lot_size",
        "brif": "Standardized Forex trade volume in lots",
        "calcuation": "size / 100,000",
        "remars": "Standard FX volume representation (e.g. 0.01 micro lot, 0.10 mini lot, 1.00 standard lot)",
    },
    "risk_amount": {
        "clmn_name": "risk_amount",
        "brif": "Total monetary capital risked on the trade ($)",
        "calcuation": "risk_safe * size (equals fixed risk_per_trade parameter, e.g. $100.00)",
        "remars": "Normalization denominator for R-multiple return calculations",
    },
    "entry_fees": {
        "clmn_name": "entry_fees",
        "brif": "Broker transaction fee / commission incurred upon trade entry",
        "calcuation": "Fixed or spread-based fee applied on entry fill",
        "remars": "Deducted from gross realized PnL",
    },
    "exit_fees": {
        "clmn_name": "exit_fees",
        "brif": "Broker transaction fee / commission incurred upon trade exit",
        "calcuation": "Fixed or spread-based fee applied on exit fill",
        "remars": "Deducted from gross realized PnL",
    },

    # 8. Risk:Reward & Realized Expectancy
    "projected_rr": {
        "clmn_name": "projected_rr",
        "brif": "Projected Risk:Reward ratio using safe SL (legacy duplicate of projected_rr_safe)",
        "calcuation": "(tp_price - entry_price) / risk_safe",
        "remars": "Purged in v6; retained in v5 for backwards compatibility",
    },
    "projected_rr_safe": {
        "clmn_name": "projected_rr_safe",
        "brif": "Projected Risk:Reward ratio using dynamic safe Stop Loss",
        "calcuation": "(tp_price - entry_price) / risk_safe",
        "remars": "Canonical metric; expected return multiple if trade reaches TP",
    },
    "projected_rr_primary": {
        "clmn_name": "projected_rr_primary",
        "brif": "Projected Risk:Reward ratio using aggressive primary Stop Loss",
        "calcuation": "(tp_price - entry_price) / risk_primary",
        "remars": "Evaluates R:R potential if using tighter primary SL",
    },
    "r_multiple": {
        "clmn_name": "r_multiple",
        "brif": "Realized normalized return multiple",
        "calcuation": "pnl / risk_amount",
        "remars": "Unit-less normalized payoff (e.g. +1.85R on win, -1.00R on full loss)",
    },
    "pnl": {
        "clmn_name": "pnl",
        "brif": "Total net realized monetary profit/loss in currency units ($)",
        "calcuation": "realized_pnl * size - (entry_fees + exit_fees)",
        "remars": "Realized dollar outcome for portfolio equity curve",
    },
    "realized_pnl": {
        "clmn_name": "realized_pnl",
        "brif": "Absolute trade price point gain or loss",
        "calcuation": "exit_price - entry_price",
        "remars": "Raw point return between exit and entry price",
    },
    "return_pct": {
        "clmn_name": "return_pct",
        "brif": "Net percentage return as decimal fraction",
        "calcuation": "realized_pnl / entry_price",
        "remars": "Fractional return (e.g. +0.0050 for +0.50%) used in compounding",
    },
    "realized_pnl_pct": {
        "clmn_name": "realized_pnl_pct",
        "brif": "Percentage return on trade",
        "calcuation": "(realized_pnl / entry_price) * 100",
        "remars": "Percentage representation of price point return",
    },
    "is_win": {
        "clmn_name": "is_win",
        "brif": "Binary trade outcome classification flag",
        "calcuation": "1 if exit_reason == 'TP' else -1 if exit_reason == 'SL' else 0",
        "remars": "1 for profitable target hit, -1 for stop loss hit",
    },
    "exit_reason": {
        "clmn_name": "exit_reason",
        "brif": "Categorical trade termination classification trigger ('TP' | 'SL' | 'CLOSED')",
        "calcuation": "'TP' if High >= tp_price else 'SL' if Low <= safe_sl else 'CLOSED'",
        "remars": "Root cause of trade termination",
    },

    # 9. Duration & Holding Telemetry
    "holding_bars": {
        "clmn_name": "holding_bars",
        "brif": "Total number of candles elapsed from entry_time to exit_time",
        "calcuation": "exit_bar_index - entry_bar_index",
        "remars": "Trade holding duration measured in candlestick periods",
    },
    "holding_seconds": {
        "clmn_name": "holding_seconds",
        "brif": "Total wall-clock duration of active trade in seconds",
        "calcuation": "(exit_time - entry_time).total_seconds()",
        "remars": "Wall-clock elapsed duration of active position",
    },

    # 10. In-Trade Excursions (MFE/MAE/BSL)
    "mfe": {
        "clmn_name": "mfe",
        "brif": "Maximum Favorable Excursion (highest unrealized profit peak)",
        "calcuation": "max(High[entry..exit]) - entry_price",
        "remars": "Peak point profit experienced while in trade; reveals near-miss winners",
    },
    "mae": {
        "clmn_name": "mae",
        "brif": "Maximum Adverse Excursion (deepest unrealized drawdown)",
        "calcuation": "entry_price - min(Low[entry..exit])",
        "remars": "Peak point loss experienced while in trade; reveals required stop tolerance",
    },
    "fib_bsl": {
        "clmn_name": "fib_bsl",
        "brif": "In-trade maximum Fibonacci extension ratio reached before Stop Loss",
        "calcuation": "max ratio in (0.236, 0.382, 0.500, 0.618, 0.786) touched before SL; 0.786 on TP",
        "remars": "In-trade bounce strength level; indicates how close a loss trade got to target",
    },
    "fib_bsl_ambiguous": {
        "clmn_name": "fib_bsl_ambiguous",
        "brif": "Ambiguity flag for same-bar in-trade Fibonacci touch",
        "calcuation": "True if highest in-trade Fibonacci touch occurred on the exact same bar where SL hit else False",
        "remars": "Flags potential intra-bar sequence ambiguity between touch and stop exit",
    },

    # 11. Strategy-Level Post-Trade pfib (15, 30, 60 bars)
    "pfib15_bsl": {
        "clmn_name": "pfib15_bsl",
        "brif": "Post-trade runner Fibonacci extension reached within 15 bars post-exit",
        "calcuation": "Highest ratio in 14-level grid (0.236..3.000) reached before hitting entry_price (BE) or safe_sl",
        "remars": "Evaluated across Exit + 1..15 candles; invalidates to 0.0 if BE or SL breached before reaching ratio",
    },
    "pfib15_be_hit": {
        "clmn_name": "pfib15_be_hit",
        "brif": "Post-trade Breakeven breach flag within 15 bars post-exit",
        "calcuation": "True if min(Low) <= entry_price within 15 bars following trade exit else False",
        "remars": "Determines if runner continuation would have been stopped out at breakeven within 15 bars",
    },
    "pfib15_sl_hit": {
        "clmn_name": "pfib15_sl_hit",
        "brif": "Post-trade Stop Loss breach flag within 15 bars post-exit",
        "calcuation": "True if min(Low) <= safe_sl within 15 bars following trade exit else False",
        "remars": "Evaluates deep adverse excursion following trade exit within 15 bars",
    },
    "pfib30_bsl": {
        "clmn_name": "pfib30_bsl",
        "brif": "Post-trade runner Fibonacci extension reached within 30 bars post-exit",
        "calcuation": "Highest ratio in 14-level grid (0.236..3.000) reached before hitting entry_price (BE) or safe_sl",
        "remars": "Evaluated across Exit + 1..30 candles; invalidates to 0.0 if BE or SL breached before reaching ratio",
    },
    "pfib30_be_hit": {
        "clmn_name": "pfib30_be_hit",
        "brif": "Post-trade Breakeven breach flag within 30 bars post-exit",
        "calcuation": "True if min(Low) <= entry_price within 30 bars following trade exit else False",
        "remars": "Determines if runner continuation would have been stopped out at breakeven within 30 bars",
    },
    "pfib30_sl_hit": {
        "clmn_name": "pfib30_sl_hit",
        "brif": "Post-trade Stop Loss breach flag within 30 bars post-exit",
        "calcuation": "True if min(Low) <= safe_sl within 30 bars following trade exit else False",
        "remars": "Evaluates deep adverse excursion following trade exit within 30 bars",
    },
    "pfib60_bsl": {
        "clmn_name": "pfib60_bsl",
        "brif": "Post-trade runner Fibonacci extension reached within 60 bars post-exit",
        "calcuation": "Highest ratio in 14-level grid (0.236..3.000) reached before hitting entry_price (BE) or safe_sl",
        "remars": "Evaluated across Exit + 1..60 candles; invalidates to 0.0 if BE or SL breached before reaching ratio",
    },
    "pfib60_be_hit": {
        "clmn_name": "pfib60_be_hit",
        "brif": "Post-trade Breakeven breach flag within 60 bars post-exit",
        "calcuation": "True if min(Low) <= entry_price within 60 bars following trade exit else False",
        "remars": "Determines if runner continuation would have been stopped out at breakeven within 60 bars",
    },
    "pfib60_sl_hit": {
        "clmn_name": "pfib60_sl_hit",
        "brif": "Post-trade Stop Loss breach flag within 60 bars post-exit",
        "calcuation": "True if min(Low) <= safe_sl within 60 bars following trade exit else False",
        "remars": "Evaluates deep adverse excursion following trade exit within 60 bars",
    },

    # 12. Execution Controls & Multi-Trade
    "allow_concurrent_trades": {
        "clmn_name": "allow_concurrent_trades",
        "brif": "Execution control toggle permitting or suppressing concurrent positions",
        "calcuation": "True if overlapping positions permitted else False",
        "remars": "If False, new signals during active trades are suppressed; if True, tracked independently",
    },
    "concurrent_trades_count": {
        "clmn_name": "concurrent_trades_count",
        "brif": "Simultaneous active trade count open on current bar",
        "calcuation": "len(active_trades) on current candle",
        "remars": "Bar-level portfolio margin exposure telemetry",
    },

    # 13. 3-Candle State Patterns
    "epatt_1": {
        "clmn_name": "epatt_1",
        "brif": "3-candle setup state pattern strictly before entry bar",
        "calcuation": "pos(-3) || '-' || pos(-2) || '-' || pos(-1) in Direction+Color format (e.g. 'DR-DR-UG')",
        "remars": "Canonical replacement for entry_1; primary classification for loss profiling",
    },
    "epatt_2": {
        "clmn_name": "epatt_2",
        "brif": "3-candle pattern: 2 setup candles before entry + entry candle",
        "calcuation": "pos(-2) || '-' || pos(-1) || '-' || pos(0) in Direction+Color format (e.g. 'DR-UG-UG')",
        "remars": "Canonical replacement for entry_2; includes entry candle state",
    },
    "epatt_3": {
        "clmn_name": "epatt_3",
        "brif": "3-candle straddle pattern centered on entry candle",
        "calcuation": "pos(-1) || '-' || pos(0) || '-' || pos(+1) in Direction+Color format (e.g. 'UG-UG-UR')",
        "remars": "Canonical replacement for entry_3; captures entry transition",
    },
    "epatt_4": {
        "clmn_name": "epatt_4",
        "brif": "4-candle forward follow-through pattern starting from entry",
        "calcuation": "pos(0) || '-' || pos(+1) || '-' || pos(+2) || '-' || pos(+3) (e.g. 'UG-UR-DG-UG')",
        "remars": "Canonical replacement for entry_4; measures post-entry momentum follow-through",
    },
    "entry_1": {
        "clmn_name": "entry_1",
        "brif": "3-candle setup state pattern prior to entry (legacy duplicate of epatt_1)",
        "calcuation": "pos(-3) || '-' || pos(-2) || '-' || pos(-1)",
        "remars": "Purged in v6; retained in v5 for backwards compatibility with legacy loss-profile queries",
    },
    "entry_2": {
        "clmn_name": "entry_2",
        "brif": "2 setup candles before entry + entry candle (legacy duplicate of epatt_2)",
        "calcuation": "pos(-2) || '-' || pos(-1) || '-' || pos(0)",
        "remars": "Purged in v6; retained in v5 for backwards compatibility with legacy loss-profile queries",
    },
    "entry_3": {
        "clmn_name": "entry_3",
        "brif": "Straddle pattern centered on entry candle (legacy duplicate of epatt_3)",
        "calcuation": "pos(-1) || '-' || pos(0) || '-' || pos(+1)",
        "remars": "Purged in v6; retained in v5 for backwards compatibility with legacy loss-profile queries",
    },
    "entry_4": {
        "clmn_name": "entry_4",
        "brif": "4-candle forward follow-through pattern (legacy duplicate of epatt_4)",
        "calcuation": "pos(0) || '-' || pos(+1) || '-' || pos(+2) || '-' || pos(+3)",
        "remars": "Purged in v6; retained in v5 for backwards compatibility with legacy loss-profile queries",
    },

    # 14. TA Candlestick Classifications
    "ecpatt_1": {
        "clmn_name": "ecpatt_1",
        "brif": "1st detected technical analysis candlestick pattern name on confirmation bar",
        "calcuation": "Detected TA pattern (e.g. 'Hammer', 'Bullish_Engulfing') on Bar +3",
        "remars": "Computed via ta_patterns_book.loss_profile.candles",
    },
    "ecpatt_2": {
        "clmn_name": "ecpatt_2",
        "brif": "2nd detected technical analysis candlestick pattern name on confirmation bar",
        "calcuation": "2nd detected TA pattern on Bar +3",
        "remars": "Computed via ta_patterns_book.loss_profile.candles",
    },
    "ecpatt_3": {
        "clmn_name": "ecpatt_3",
        "brif": "3rd detected technical analysis candlestick pattern name on confirmation bar",
        "calcuation": "3rd detected TA pattern on Bar +3",
        "remars": "Computed via ta_patterns_book.loss_profile.candles",
    },
    "epcpatt_1": {
        "clmn_name": "epcpatt_1",
        "brif": "1st detected technical analysis candlestick pattern name on setup trigger bar (Bar 0)",
        "calcuation": "Detected TA pattern on initial signal candle",
        "remars": "Computed via ta_patterns_book.loss_profile.candles",
    },
    "epcpatt_2": {
        "clmn_name": "epcpatt_2",
        "brif": "2nd detected technical analysis candlestick pattern name on setup trigger bar (Bar 0)",
        "calcuation": "2nd detected TA pattern on initial signal candle",
        "remars": "Computed via ta_patterns_book.loss_profile.candles",
    },
    "epcpatt_3": {
        "clmn_name": "epcpatt_3",
        "brif": "3rd detected technical analysis candlestick pattern name on setup trigger bar (Bar 0)",
        "calcuation": "3rd detected TA pattern on initial signal candle",
        "remars": "Computed via ta_patterns_book.loss_profile.candles",
    },

    # 15. Simulation & Signal Flow
    "entries": {
        "clmn_name": "entries",
        "brif": "Boolean entry signal execution flag on confirmation candle Open",
        "calcuation": "True on confirmation bar Open (Bar +3), False otherwise",
        "remars": "Used in VectorBT portfolio simulation and bar-level signals",
    },
    "exits": {
        "clmn_name": "exits",
        "brif": "Boolean exit signal execution flag on trade termination candle",
        "calcuation": "True on candle where TP, SL, or cutoff triggers, False otherwise",
        "remars": "Used in VectorBT portfolio simulation and bar-level signals",
    },
    "in_trade": {
        "clmn_name": "in_trade",
        "brif": "Boolean active position state flag",
        "calcuation": "True for all bars while position is open, False otherwise",
        "remars": "Bar-level position state telemetry",
    },
}

# V6 Canonical Columns Order (69 columns)
V6_CANONICAL_COLUMNS = [
    # Metadata & Timestamps
    "uid", "trade_id", "vbt_trade_id", "fingerprint", "strategy_name", "symbol", "timeframe", "direction", "status", "session",
    "signal_time", "confirmation_time", "entry_time", "exit_time",
    # Order levels & pivots
    "entry_price", "exit_price", "tp_price", "swing_low", "pivot", "lower_pivot", "upper_pivot",
    # SL hierarchy & breach flags
    "primary_sl", "pivot_sl", "safe_sl", "primary_sl_hit", "pivot_sl_hit", "safe_sl_hit",
    # Risk & Expectancy
    "risk_primary", "risk_pivot", "risk_safe", "size", "lot_size", "risk_amount", "entry_fees", "exit_fees",
    "projected_rr_safe", "projected_rr_primary", "r_multiple", "pnl", "realized_pnl", "return_pct", "realized_pnl_pct", "is_win", "exit_reason",
    # Duration & In-Trade Excursions
    "holding_bars", "holding_seconds", "mfe", "mae", "fib_bsl", "fib_bsl_ambiguous",
    # Post-Trade pfib
    "pfib15_bsl", "pfib15_be_hit", "pfib15_sl_hit",
    "pfib30_bsl", "pfib30_be_hit", "pfib30_sl_hit",
    "pfib60_bsl", "pfib60_be_hit", "pfib60_sl_hit",
    # Multi-trade execution
    "allow_concurrent_trades", "concurrent_trades_count",
    # Patterns
    "epatt_1", "epatt_2", "epatt_3", "epatt_4",
    "ecpatt_1", "ecpatt_2", "ecpatt_3", "epcpatt_1", "epcpatt_2", "epcpatt_3",
]


def get_target_db_columns(con: duckdb.DuckDBPyConnection) -> set[str]:
    """Retrieve all column names present in trade tables in target DuckDB."""
    existing_cols = set()
    tables = [t[0] for t in con.execute("SHOW TABLES").fetchall()]
    for t in tables:
        if "trade" in t.lower():
            cols = [c[0] for c in con.execute(f"DESCRIBE {t}").fetchall()]
            existing_cols.update(cols)
    return existing_cols


def build_info_records(
    strategy_name: str = "classic_floor_mod_v6",
    existing_columns: set[str] | None = None,
) -> list[dict[str, str]]:
    """Build structured info records matching the requested schema.

    Schema: (clmn_name, brif, calcuation, remars)
    """
    records: list[dict[str, str]] = []
    seen = set()

    # Determine priority column ordering based on strategy
    if "v6" in strategy_name.lower():
        priority_cols = V6_CANONICAL_COLUMNS
    else:
        # For v5 or generic, start with all known dictionary keys
        priority_cols = list(COLUMN_DICTIONARY.keys())

    # Add columns in priority order
    for col in priority_cols:
        if col in COLUMN_DICTIONARY and col not in seen:
            records.append(COLUMN_DICTIONARY[col])
            seen.add(col)

    # If target database has additional columns present, add them too
    if existing_columns:
        for col in sorted(existing_columns):
            if col not in seen:
                if col in COLUMN_DICTIONARY:
                    records.append(COLUMN_DICTIONARY[col])
                else:
                    records.append({
                        "clmn_name": col,
                        "brif": f"Dynamic strategy column '{col}'",
                        "calcuation": "Extracted from source trade dataset",
                        "remars": "Auto-registered from existing target table schema",
                    })
                seen.add(col)

    return records


def pack_info_table(
    target_db: str,
    strategy_name: str = "classic_floor_mod_v6",
    table_name: str = "info",
    dry_run: bool = False,
) -> int:
    """Insert or replace the 'info' table in the target DuckDB database."""
    target_path = Path(target_db).resolve()
    if not dry_run and not target_path.exists():
        console.print(f"[yellow]Target database {target_path} does not exist. Creating new database.[/yellow]")

    # Inspect existing tables and columns in target DB
    existing_cols: set[str] = set()
    if target_path.exists():
        try:
            inspect_con = duckdb.connect(str(target_path), read_only=True)
            existing_cols = get_target_db_columns(inspect_con)
            inspect_con.close()
        except Exception:
            existing_cols = set()

    records = build_info_records(strategy_name=strategy_name, existing_columns=existing_cols)
    df_info = pd.DataFrame(records)[["clmn_name", "brif", "calcuation", "remars"]]

    if dry_run:
        console.print(f"[bold yellow][DRY-RUN][/bold yellow] Would insert {len(df_info)} rows into '{table_name}' in {target_path}")
    else:
        con = duckdb.connect(str(target_path), read_only=False)
        con.register("df_info_temp", df_info)
        con.execute(f"""
            CREATE OR REPLACE TABLE {table_name} (
                clmn_name VARCHAR PRIMARY KEY,
                brif VARCHAR,
                calcuation VARCHAR,
                remars VARCHAR
            )
        """)
        con.execute(f"INSERT INTO {table_name} SELECT * FROM df_info_temp")
        con.close()
        console.print(f"[bold green]✓ Successfully packed {len(df_info)} column definitions into '{table_name}' table in {target_path.name}[/bold green]")

    # Render summary table conforming to project borderless formatting standards
    table = Table(
        title=f"Metadata Dictionary ('{table_name}' table in {target_path.name})",
        box=None,
        show_header=True,
        header_style="bold cyan",
        show_edge=False,
        pad_edge=False,
    )
    table.add_column("#", justify="right", style="dim", width=4)
    table.add_column("clmn_name", style="bold green", min_width=18)
    table.add_column("brif", style="white", min_width=32)
    table.add_column("calcuation", style="cyan", min_width=36)
    table.add_column("remars", style="dim white", min_width=32)

    # Preview first 15 entries in console
    preview_limit = min(15, len(df_info))
    for i in range(preview_limit):
        row = df_info.iloc[i]
        table.add_row(
            str(i + 1),
            str(row["clmn_name"]),
            str(row["brif"])[:40] + ("..." if len(str(row["brif"])) > 40 else ""),
            str(row["calcuation"])[:44] + ("..." if len(str(row["calcuation"])) > 44 else ""),
            str(row["remars"])[:38] + ("..." if len(str(row["remars"])) > 38 else ""),
        )

    console.print(table)
    if len(df_info) > preview_limit:
        console.print(f"[dim]... and {len(df_info) - preview_limit} more columns documented in '{table_name}'.[/dim]\n")

    return len(df_info)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Insert column metadata table (clmn_name, brif, calcuation, remars) into target DuckDB."
    )
    parser.add_argument(
        "--target",
        "-t",
        required=True,
        help="Path to the target DuckDB file (e.g. Shared/Data/classic_floor_mod-v5-1.duckdb)",
    )
    parser.add_argument(
        "--strategy",
        "-s",
        default="classic_floor_mod_v6",
        help="Strategy name to document (default: classic_floor_mod_v6)",
    )
    parser.add_argument(
        "--table",
        default="info",
        help="Table name to create in target DuckDB (default: 'info')",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview table creation without committing changes to disk",
    )

    args = parser.parse_args()

    # Detect strategy from invoked script name if default
    script_basename = Path(sys.argv[0]).stem
    strategy = args.strategy
    if strategy == "classic_floor_mod_v6" and "v5" in script_basename:
        strategy = "classic_floor_mod_v5"

    pack_info_table(
        target_db=args.target,
        strategy_name=strategy,
        table_name=args.table,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    main()
